#!/bin/bash
#
# Script to setup Raspi to run RTL_SDR
# 

# Not required on Raspian
# sudo apt-get install git

sudo apt-get install cmake

sudo apt-get install pkg-config

sudo apt-get install libusb-1.0

# get rtl_sdr
git clone git://git.osmocom.org/rtl-sdr.git 

cd rtl-sdr
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig

# Get dump1090
git clone https://github.com/antirez/dump1090.git

cd dump1090
make
cd ..


#
#  Setup wireless
#
#cd ../../
#sudo cp wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
#echo "make sure to update wireless network settings in /etc/wpa_supplicant/wpa_supplicant.conf if you didn't before running this script"
#echo " to test wireless: sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf "

#
# Get stuffs for RTL-power and heatmap script
#
cd /home/pi
wget http://kmkeen.com/tmp/heatmap.py.txt
mv heatmap.py.txt heatmap.py
cd /usr/bin
sudo ln -s python2.7 python2
# PIL needed for heatmap script
sudo apt-get install python-imaging
#
cd /home/pi
diff /home/pi/heatmap.py /home/pi/msproj1/heatmap.py
#Just checking if source updated
exit
