#!/bin/bash
#
# Script to setup Raspi to run RTL_SDR
#

# Not required on Raspian
# sudo apt-get install git

sudo apt-get install cmake

sudo apt-get install pkg-config

sudo apt-get install libusb-1.0


git clone git://git.osmocom.org/rtl-sdr.git

cd rtl-sdr
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig

#
#  Setup wireless
#



sudo cp wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf

echo "make sure to update wireless network settings in /etc/wpa_supplicant/wpa_supplicant.conf if you didn't before running this script"

echo " to test wireless: sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf "

exit