#!/bin/bash
#
# Script to setup Raspi to run RTL_SDR
#

# Not required on Raspian
# sudo apt-get install git

sudo apt-get install cmake

sudo apt-get install pkg-config

sudo apt-get install libusb-1.0


git clone git://git.osmocom.org/rtl-sdr.git

cd rtl-sdr
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig

exit